// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contracts

import "encoding/json"
import "errors"
import "fmt"
import "reflect"
import "time"

// A remediation Pantheon proposes, and may later execute.
type Action struct {
	// ApprovalState corresponds to the JSON schema field "approval_state".
	ApprovalState ApprovalState `json:"approval_state,omitempty,omitzero" yaml:"approval_state,omitempty" mapstructure:"approval_state,omitempty"`

	// BlastRadius corresponds to the JSON schema field "blast_radius".
	BlastRadius BlastRadius `json:"blast_radius" yaml:"blast_radius" mapstructure:"blast_radius"`

	// Dry run until explicitly cleared.
	DryRun bool `json:"dry_run,omitempty,omitzero" yaml:"dry_run,omitempty" mapstructure:"dry_run,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// What it does, e.g. 'rollout_restart'.
	Operation string `json:"operation" yaml:"operation" mapstructure:"operation"`

	// Why this Action was proposed.
	Reason interface{} `json:"reason,omitempty,omitzero" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// What it acts on, e.g. 'deployment/checkout'.
	Target string `json:"target" yaml:"target" mapstructure:"target"`
}

type ActionReason_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Action) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["blast_radius"]; raw != nil && !ok {
		return fmt.Errorf("field blast_radius in Action: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Action: required")
	}
	if _, ok := raw["operation"]; raw != nil && !ok {
		return fmt.Errorf("field operation in Action: required")
	}
	if _, ok := raw["target"]; raw != nil && !ok {
		return fmt.Errorf("field target in Action: required")
	}
	type Plain Action
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["approval_state"]; !ok || v == nil {
		plain.ApprovalState = "pending"
	}
	if v, ok := raw["dry_run"]; !ok || v == nil {
		plain.DryRun = true
	}
	*j = Action(plain)
	return nil
}

// Ceilings the dispatcher enforces for a single agent invocation.
type AgentBudget struct {
	// MaxSeconds corresponds to the JSON schema field "max_seconds".
	MaxSeconds int `json:"max_seconds" yaml:"max_seconds" mapstructure:"max_seconds"`

	// MaxTokens corresponds to the JSON schema field "max_tokens".
	MaxTokens int `json:"max_tokens" yaml:"max_tokens" mapstructure:"max_tokens"`

	// MaxToolCalls corresponds to the JSON schema field "max_tool_calls".
	MaxToolCalls int `json:"max_tool_calls" yaml:"max_tool_calls" mapstructure:"max_tool_calls"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentBudget) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["max_seconds"]; raw != nil && !ok {
		return fmt.Errorf("field max_seconds in AgentBudget: required")
	}
	if _, ok := raw["max_tokens"]; raw != nil && !ok {
		return fmt.Errorf("field max_tokens in AgentBudget: required")
	}
	if _, ok := raw["max_tool_calls"]; raw != nil && !ok {
		return fmt.Errorf("field max_tool_calls in AgentBudget: required")
	}
	type Plain AgentBudget
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain.MaxSeconds {
		return fmt.Errorf("field %s: must be > %v", "max_seconds", 0)
	}
	if 0 >= plain.MaxTokens {
		return fmt.Errorf("field %s: must be > %v", "max_tokens", 0)
	}
	if 0 >= plain.MaxToolCalls {
		return fmt.Errorf("field %s: must be > %v", "max_tool_calls", 0)
	}
	*j = AgentBudget(plain)
	return nil
}

// Everything the registry needs to know about an agent without importing it.
type AgentManifest struct {
	// Budget corresponds to the JSON schema field "budget".
	Budget AgentBudget `json:"budget" yaml:"budget" mapstructure:"budget"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities []Capability `json:"capabilities,omitempty,omitzero" yaml:"capabilities,omitempty" mapstructure:"capabilities,omitempty"`

	// Mythological name, e.g. 'argus'.
	Codename string `json:"codename" yaml:"codename" mapstructure:"codename"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Folder under agents/, e.g. 'anomaly'.
	Domain string `json:"domain" yaml:"domain" mapstructure:"domain"`

	// Connector tools this agent may call.
	Tools []string `json:"tools,omitempty,omitzero" yaml:"tools,omitempty" mapstructure:"tools,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["budget"]; raw != nil && !ok {
		return fmt.Errorf("field budget in AgentManifest: required")
	}
	if _, ok := raw["codename"]; raw != nil && !ok {
		return fmt.Errorf("field codename in AgentManifest: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in AgentManifest: required")
	}
	if _, ok := raw["domain"]; raw != nil && !ok {
		return fmt.Errorf("field domain in AgentManifest: required")
	}
	type Plain AgentManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AgentManifest(plain)
	return nil
}

// An Action needs a human before it can execute.
type ApprovalRequestedEvent struct {
	// Action corresponds to the JSON schema field "action".
	Action Action `json:"action" yaml:"action" mapstructure:"action"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRequestedEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in ApprovalRequestedEvent: required")
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in ApprovalRequestedEvent: required")
	}
	type Plain ApprovalRequestedEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "approval_requested"
	}
	if plain.Type != "approval_requested" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "approval_requested")
	}
	*j = ApprovalRequestedEvent(plain)
	return nil
}

type ApprovalState string

const ApprovalStateApproved ApprovalState = "approved"
const ApprovalStateNotRequired ApprovalState = "not_required"
const ApprovalStatePending ApprovalState = "pending"
const ApprovalStateRejected ApprovalState = "rejected"

var enumValues_ApprovalState = []interface{}{
	"not_required",
	"pending",
	"approved",
	"rejected",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalState, v)
	}
	*j = ApprovalState(v)
	return nil
}

type BlastRadius string

const BlastRadiusCluster BlastRadius = "cluster"
const BlastRadiusNamespace BlastRadius = "namespace"
const BlastRadiusNone BlastRadius = "none"
const BlastRadiusSingleWorkload BlastRadius = "single_workload"

var enumValues_BlastRadius = []interface{}{
	"none",
	"single_workload",
	"namespace",
	"cluster",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BlastRadius) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BlastRadius {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BlastRadius, v)
	}
	*j = BlastRadius(v)
	return nil
}

// One thing an agent claims it can do.
type Capability struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Stable identifier, e.g. 'detect_metric_anomaly'.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Capability) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in Capability: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in Capability: required")
	}
	type Plain Capability
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Capability(plain)
	return nil
}

// Transport wrapper carrying one event plus its correlation metadata.
type EventEnvelope struct {
	// EmittedAt corresponds to the JSON schema field "emitted_at".
	EmittedAt time.Time `json:"emitted_at" yaml:"emitted_at" mapstructure:"emitted_at"`

	// Event corresponds to the JSON schema field "event".
	Event interface{} `json:"event" yaml:"event" mapstructure:"event"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventEnvelope) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["emitted_at"]; raw != nil && !ok {
		return fmt.Errorf("field emitted_at in EventEnvelope: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventEnvelope: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in EventEnvelope: required")
	}
	type Plain EventEnvelope
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EventEnvelope(plain)
	return nil
}

// A single observation, attributable to one connector at one moment.
type Evidence struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EvidenceKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// ObservedAt corresponds to the JSON schema field "observed_at".
	ObservedAt time.Time `json:"observed_at" yaml:"observed_at" mapstructure:"observed_at"`

	// Kind-specific body. Phase 1 replaces this with per-kind models.
	Payload EvidencePayload `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source EvidenceSource `json:"source" yaml:"source" mapstructure:"source"`

	// One-line human-readable description.
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

type EvidenceKind string

const EvidenceKindK8SEvent EvidenceKind = "k8s_event"
const EvidenceKindLogCluster EvidenceKind = "log_cluster"
const EvidenceKindManifestDiff EvidenceKind = "manifest_diff"
const EvidenceKindMetricWindow EvidenceKind = "metric_window"
const EvidenceKindPipelineRun EvidenceKind = "pipeline_run"

var enumValues_EvidenceKind = []interface{}{
	"metric_window",
	"log_cluster",
	"manifest_diff",
	"k8s_event",
	"pipeline_run",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EvidenceKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EvidenceKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EvidenceKind, v)
	}
	*j = EvidenceKind(v)
	return nil
}

// Kind-specific body. Phase 1 replaces this with per-kind models.
type EvidencePayload map[string]interface{}

// Where a piece of Evidence came from, so a human can go look themselves.
type EvidenceSource struct {
	// Connector that produced it, e.g. 'prometheus'.
	Connector string `json:"connector" yaml:"connector" mapstructure:"connector"`

	// Query that produced it, if any.
	Query interface{} `json:"query,omitempty,omitzero" yaml:"query,omitempty" mapstructure:"query,omitempty"`
}

type EvidenceSourceQuery_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *EvidenceSource) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connector"]; raw != nil && !ok {
		return fmt.Errorf("field connector in EvidenceSource: required")
	}
	type Plain EvidenceSource
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EvidenceSource(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Evidence) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Evidence: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Evidence: required")
	}
	if _, ok := raw["observed_at"]; raw != nil && !ok {
		return fmt.Errorf("field observed_at in Evidence: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in Evidence: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Evidence: required")
	}
	type Plain Evidence
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Evidence(plain)
	return nil
}

// One agent's supported claim about what it observed.
type Finding struct {
	// Codename of the agent that produced it, e.g. 'argus'.
	Agent string `json:"agent" yaml:"agent" mapstructure:"agent"`

	// Agent's own confidence, 0 to 1.
	Confidence float64 `json:"confidence" yaml:"confidence" mapstructure:"confidence"`

	// Evidence supporting the claim. A Finding with none is inadmissible.
	Evidence []Evidence `json:"evidence,omitempty,omitzero" yaml:"evidence,omitempty" mapstructure:"evidence,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Why the Evidence supports the claim.
	Rationale interface{} `json:"rationale,omitempty,omitzero" yaml:"rationale,omitempty" mapstructure:"rationale,omitempty"`

	// Severity corresponds to the JSON schema field "severity".
	Severity Severity `json:"severity" yaml:"severity" mapstructure:"severity"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

// An agent returned a Finding.
type FindingProducedEvent struct {
	// Finding corresponds to the JSON schema field "finding".
	Finding Finding `json:"finding" yaml:"finding" mapstructure:"finding"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FindingProducedEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["finding"]; raw != nil && !ok {
		return fmt.Errorf("field finding in FindingProducedEvent: required")
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in FindingProducedEvent: required")
	}
	type Plain FindingProducedEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "finding_produced"
	}
	if plain.Type != "finding_produced" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "finding_produced")
	}
	*j = FindingProducedEvent(plain)
	return nil
}

type FindingRationale_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Finding) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent"]; raw != nil && !ok {
		return fmt.Errorf("field agent in Finding: required")
	}
	if _, ok := raw["confidence"]; raw != nil && !ok {
		return fmt.Errorf("field confidence in Finding: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Finding: required")
	}
	if _, ok := raw["severity"]; raw != nil && !ok {
		return fmt.Errorf("field severity in Finding: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Finding: required")
	}
	type Plain Finding
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 < plain.Confidence {
		return fmt.Errorf("field %s: must be <= %v", "confidence", 1)
	}
	if 0 > plain.Confidence {
		return fmt.Errorf("field %s: must be >= %v", "confidence", 0)
	}
	*j = Finding(plain)
	return nil
}

// One end-to-end run, from trigger to Verdict.
type Investigation struct {
	// CompletedAt corresponds to the JSON schema field "completed_at".
	CompletedAt *time.Time `json:"completed_at,omitempty,omitzero" yaml:"completed_at,omitempty" mapstructure:"completed_at,omitempty"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Findings corresponds to the JSON schema field "findings".
	Findings []Finding `json:"findings,omitempty,omitzero" yaml:"findings,omitempty" mapstructure:"findings,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// State corresponds to the JSON schema field "state".
	State InvestigationState `json:"state" yaml:"state" mapstructure:"state"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger Trigger `json:"trigger" yaml:"trigger" mapstructure:"trigger"`

	// Absent until the run reaches a conclusion.
	Verdict *InvestigationVerdict `json:"verdict,omitempty,omitzero" yaml:"verdict,omitempty" mapstructure:"verdict,omitempty"`
}

// An Investigation moved out of PENDING.
type InvestigationStartedEvent struct {
	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvestigationStartedEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in InvestigationStartedEvent: required")
	}
	type Plain InvestigationStartedEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "investigation_started"
	}
	if plain.Type != "investigation_started" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "investigation_started")
	}
	*j = InvestigationStartedEvent(plain)
	return nil
}

type InvestigationState string

const InvestigationStateAwaitingApproval InvestigationState = "awaiting_approval"
const InvestigationStateCancelled InvestigationState = "cancelled"
const InvestigationStateCompleted InvestigationState = "completed"
const InvestigationStateFailed InvestigationState = "failed"
const InvestigationStatePending InvestigationState = "pending"
const InvestigationStatePlanning InvestigationState = "planning"
const InvestigationStateRunning InvestigationState = "running"

var enumValues_InvestigationState = []interface{}{
	"pending",
	"planning",
	"running",
	"awaiting_approval",
	"completed",
	"failed",
	"cancelled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvestigationState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InvestigationState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InvestigationState, v)
	}
	*j = InvestigationState(v)
	return nil
}

// Absent until the run reaches a conclusion.
type InvestigationVerdict struct {
	// Confidence corresponds to the JSON schema field "confidence".
	Confidence float64 `json:"confidence" yaml:"confidence" mapstructure:"confidence"`

	// ContributingFindings corresponds to the JSON schema field
	// "contributing_findings".
	ContributingFindings []Finding `json:"contributing_findings,omitempty,omitzero" yaml:"contributing_findings,omitempty" mapstructure:"contributing_findings,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// RecommendedActions corresponds to the JSON schema field "recommended_actions".
	RecommendedActions []Action `json:"recommended_actions,omitempty,omitzero" yaml:"recommended_actions,omitempty" mapstructure:"recommended_actions,omitempty"`

	// Null when the evidence does not support a conclusion.
	RootCause interface{} `json:"root_cause,omitempty,omitzero" yaml:"root_cause,omitempty" mapstructure:"root_cause,omitempty"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvestigationVerdict) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var investigationVerdict_0 InvestigationVerdict_0
	var errs []error
	if err := investigationVerdict_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain InvestigationVerdict
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InvestigationVerdict(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Investigation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in Investigation: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Investigation: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in Investigation: required")
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in Investigation: required")
	}
	type Plain Investigation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Investigation(plain)
	return nil
}

// Generated from core/contracts/ by codegen/export_schemas.py. Do not edit by
// hand.
type PantheonSchemaJson struct {
	// Action corresponds to the JSON schema field "action".
	Action *Action `json:"action,omitempty,omitzero" yaml:"action,omitempty" mapstructure:"action,omitempty"`

	// AgentManifest corresponds to the JSON schema field "agent_manifest".
	AgentManifest *AgentManifest `json:"agent_manifest,omitempty,omitzero" yaml:"agent_manifest,omitempty" mapstructure:"agent_manifest,omitempty"`

	// EventEnvelope corresponds to the JSON schema field "event_envelope".
	EventEnvelope *EventEnvelope `json:"event_envelope,omitempty,omitzero" yaml:"event_envelope,omitempty" mapstructure:"event_envelope,omitempty"`

	// Evidence corresponds to the JSON schema field "evidence".
	Evidence *Evidence `json:"evidence,omitempty,omitzero" yaml:"evidence,omitempty" mapstructure:"evidence,omitempty"`

	// Finding corresponds to the JSON schema field "finding".
	Finding *Finding `json:"finding,omitempty,omitzero" yaml:"finding,omitempty" mapstructure:"finding,omitempty"`

	// Investigation corresponds to the JSON schema field "investigation".
	Investigation *Investigation `json:"investigation,omitempty,omitzero" yaml:"investigation,omitempty" mapstructure:"investigation,omitempty"`

	// Verdict corresponds to the JSON schema field "verdict".
	Verdict *Verdict `json:"verdict,omitempty,omitzero" yaml:"verdict,omitempty" mapstructure:"verdict,omitempty"`
}

type Severity string

const SeverityCritical Severity = "critical"
const SeverityHigh Severity = "high"
const SeverityInfo Severity = "info"
const SeverityLow Severity = "low"
const SeverityMedium Severity = "medium"

var enumValues_Severity = []interface{}{
	"info",
	"low",
	"medium",
	"high",
	"critical",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Severity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Severity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Severity, v)
	}
	*j = Severity(v)
	return nil
}

// The inbound event that started everything.
type Trigger struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind TriggerKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload TriggerPayload `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`

	// ReceivedAt corresponds to the JSON schema field "received_at".
	ReceivedAt time.Time `json:"received_at" yaml:"received_at" mapstructure:"received_at"`

	// Who sent it, e.g. 'alertmanager'.
	Source string `json:"source" yaml:"source" mapstructure:"source"`
}

type TriggerKind string

const TriggerKindAlert TriggerKind = "alert"
const TriggerKindHumanQuestion TriggerKind = "human_question"
const TriggerKindSchedule TriggerKind = "schedule"
const TriggerKindWebhook TriggerKind = "webhook"

var enumValues_TriggerKind = []interface{}{
	"alert",
	"webhook",
	"schedule",
	"human_question",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TriggerKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TriggerKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TriggerKind, v)
	}
	*j = TriggerKind(v)
	return nil
}

type TriggerPayload map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Trigger) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Trigger: required")
	}
	if _, ok := raw["received_at"]; raw != nil && !ok {
		return fmt.Errorf("field received_at in Trigger: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in Trigger: required")
	}
	type Plain Trigger
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Trigger(plain)
	return nil
}

// The orchestrator's ranked conclusion for one Investigation.
type Verdict struct {
	// Confidence corresponds to the JSON schema field "confidence".
	Confidence float64 `json:"confidence" yaml:"confidence" mapstructure:"confidence"`

	// ContributingFindings corresponds to the JSON schema field
	// "contributing_findings".
	ContributingFindings []Finding `json:"contributing_findings,omitempty,omitzero" yaml:"contributing_findings,omitempty" mapstructure:"contributing_findings,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// RecommendedActions corresponds to the JSON schema field "recommended_actions".
	RecommendedActions []Action `json:"recommended_actions,omitempty,omitzero" yaml:"recommended_actions,omitempty" mapstructure:"recommended_actions,omitempty"`

	// Null when the evidence does not support a conclusion.
	RootCause interface{} `json:"root_cause,omitempty,omitzero" yaml:"root_cause,omitempty" mapstructure:"root_cause,omitempty"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

type VerdictRootCause_0 *string

type InvestigationVerdict_0 = Verdict

// The aggregator reached a conclusion.
type VerdictReadyEvent struct {
	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Verdict corresponds to the JSON schema field "verdict".
	Verdict Verdict `json:"verdict" yaml:"verdict" mapstructure:"verdict"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VerdictReadyEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in VerdictReadyEvent: required")
	}
	if _, ok := raw["verdict"]; raw != nil && !ok {
		return fmt.Errorf("field verdict in VerdictReadyEvent: required")
	}
	type Plain VerdictReadyEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "verdict_ready"
	}
	if plain.Type != "verdict_ready" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "verdict_ready")
	}
	*j = VerdictReadyEvent(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Verdict) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["confidence"]; raw != nil && !ok {
		return fmt.Errorf("field confidence in Verdict: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Verdict: required")
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in Verdict: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Verdict: required")
	}
	type Plain Verdict
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 < plain.Confidence {
		return fmt.Errorf("field %s: must be <= %v", "confidence", 1)
	}
	if 0 > plain.Confidence {
		return fmt.Errorf("field %s: must be >= %v", "confidence", 0)
	}
	*j = Verdict(plain)
	return nil
}
