// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package contracts

import "encoding/json"
import "errors"
import "fmt"
import "reflect"
import "time"

// A remediation Pantheon proposes, and may later execute.
type Action struct {
	// ApprovalState corresponds to the JSON schema field "approval_state".
	ApprovalState ApprovalState `json:"approval_state,omitempty,omitzero" yaml:"approval_state,omitempty" mapstructure:"approval_state,omitempty"`

	// BlastRadius corresponds to the JSON schema field "blast_radius".
	BlastRadius BlastRadius `json:"blast_radius" yaml:"blast_radius" mapstructure:"blast_radius"`

	// Dry run until explicitly cleared.
	DryRun bool `json:"dry_run,omitempty,omitzero" yaml:"dry_run,omitempty" mapstructure:"dry_run,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// What it does, e.g. 'rollout_restart'.
	Operation string `json:"operation" yaml:"operation" mapstructure:"operation"`

	// Why this Action was proposed.
	Reason interface{} `json:"reason,omitempty,omitzero" yaml:"reason,omitempty" mapstructure:"reason,omitempty"`

	// What it acts on, e.g. 'deployment/checkout'.
	Target string `json:"target" yaml:"target" mapstructure:"target"`
}

type ActionReason_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Action) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["blast_radius"]; raw != nil && !ok {
		return fmt.Errorf("field blast_radius in Action: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Action: required")
	}
	if _, ok := raw["operation"]; raw != nil && !ok {
		return fmt.Errorf("field operation in Action: required")
	}
	if _, ok := raw["target"]; raw != nil && !ok {
		return fmt.Errorf("field target in Action: required")
	}
	type Plain Action
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["approval_state"]; !ok || v == nil {
		plain.ApprovalState = "pending"
	}
	if v, ok := raw["dry_run"]; !ok || v == nil {
		plain.DryRun = true
	}
	*j = Action(plain)
	return nil
}

// Ceilings the dispatcher enforces for a single agent invocation.
type AgentBudget struct {
	// MaxSeconds corresponds to the JSON schema field "max_seconds".
	MaxSeconds int `json:"max_seconds" yaml:"max_seconds" mapstructure:"max_seconds"`

	// MaxTokens corresponds to the JSON schema field "max_tokens".
	MaxTokens int `json:"max_tokens" yaml:"max_tokens" mapstructure:"max_tokens"`

	// MaxToolCalls corresponds to the JSON schema field "max_tool_calls".
	MaxToolCalls int `json:"max_tool_calls" yaml:"max_tool_calls" mapstructure:"max_tool_calls"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentBudget) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["max_seconds"]; raw != nil && !ok {
		return fmt.Errorf("field max_seconds in AgentBudget: required")
	}
	if _, ok := raw["max_tokens"]; raw != nil && !ok {
		return fmt.Errorf("field max_tokens in AgentBudget: required")
	}
	if _, ok := raw["max_tool_calls"]; raw != nil && !ok {
		return fmt.Errorf("field max_tool_calls in AgentBudget: required")
	}
	type Plain AgentBudget
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 0 >= plain.MaxSeconds {
		return fmt.Errorf("field %s: must be > %v", "max_seconds", 0)
	}
	if 0 >= plain.MaxTokens {
		return fmt.Errorf("field %s: must be > %v", "max_tokens", 0)
	}
	if 0 >= plain.MaxToolCalls {
		return fmt.Errorf("field %s: must be > %v", "max_tool_calls", 0)
	}
	*j = AgentBudget(plain)
	return nil
}

// One thing an agent claims it can do.
type AgentCapability struct {
	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Stable identifier, e.g. 'detect_metric_anomaly'.
	Name string `json:"name" yaml:"name" mapstructure:"name"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentCapability) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in AgentCapability: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in AgentCapability: required")
	}
	type Plain AgentCapability
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AgentCapability(plain)
	return nil
}

// Everything the registry needs to know about an agent without importing it.
type AgentManifest struct {
	// Budget corresponds to the JSON schema field "budget".
	Budget AgentBudget `json:"budget" yaml:"budget" mapstructure:"budget"`

	// Capabilities corresponds to the JSON schema field "capabilities".
	Capabilities []AgentCapability `json:"capabilities,omitempty,omitzero" yaml:"capabilities,omitempty" mapstructure:"capabilities,omitempty"`

	// Mythological name, e.g. 'argus'.
	Codename string `json:"codename" yaml:"codename" mapstructure:"codename"`

	// Description corresponds to the JSON schema field "description".
	Description string `json:"description" yaml:"description" mapstructure:"description"`

	// Folder under agents/, e.g. 'anomaly'.
	Domain string `json:"domain" yaml:"domain" mapstructure:"domain"`

	// Connector tools this agent may call.
	Tools []string `json:"tools,omitempty,omitzero" yaml:"tools,omitempty" mapstructure:"tools,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AgentManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["budget"]; raw != nil && !ok {
		return fmt.Errorf("field budget in AgentManifest: required")
	}
	if _, ok := raw["codename"]; raw != nil && !ok {
		return fmt.Errorf("field codename in AgentManifest: required")
	}
	if _, ok := raw["description"]; raw != nil && !ok {
		return fmt.Errorf("field description in AgentManifest: required")
	}
	if _, ok := raw["domain"]; raw != nil && !ok {
		return fmt.Errorf("field domain in AgentManifest: required")
	}
	type Plain AgentManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AgentManifest(plain)
	return nil
}

// An Action needs a human before it can execute.
type ApprovalRequestedEvent struct {
	// Action corresponds to the JSON schema field "action".
	Action Action `json:"action" yaml:"action" mapstructure:"action"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalRequestedEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["action"]; raw != nil && !ok {
		return fmt.Errorf("field action in ApprovalRequestedEvent: required")
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in ApprovalRequestedEvent: required")
	}
	type Plain ApprovalRequestedEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "approval_requested"
	}
	if plain.Type != "approval_requested" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "approval_requested")
	}
	*j = ApprovalRequestedEvent(plain)
	return nil
}

type ApprovalState string

const ApprovalStateApproved ApprovalState = "approved"
const ApprovalStateNotRequired ApprovalState = "not_required"
const ApprovalStatePending ApprovalState = "pending"
const ApprovalStateRejected ApprovalState = "rejected"

var enumValues_ApprovalState = []interface{}{
	"not_required",
	"pending",
	"approved",
	"rejected",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ApprovalState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ApprovalState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ApprovalState, v)
	}
	*j = ApprovalState(v)
	return nil
}

type AuthMode string

const AuthModeBearer AuthMode = "bearer"
const AuthModeHeaderKey AuthMode = "header_key"
const AuthModeNone AuthMode = "none"
const AuthModeQueryParam AuthMode = "query_param"

var enumValues_AuthMode = []interface{}{
	"none",
	"bearer",
	"header_key",
	"query_param",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AuthMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AuthMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_AuthMode, v)
	}
	*j = AuthMode(v)
	return nil
}

type BlastRadius string

const BlastRadiusCluster BlastRadius = "cluster"
const BlastRadiusNamespace BlastRadius = "namespace"
const BlastRadiusNone BlastRadius = "none"
const BlastRadiusSingleWorkload BlastRadius = "single_workload"

var enumValues_BlastRadius = []interface{}{
	"none",
	"single_workload",
	"namespace",
	"cluster",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BlastRadius) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BlastRadius {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BlastRadius, v)
	}
	*j = BlastRadius(v)
	return nil
}

type Capability string

const CapabilityJsonMode Capability = "json_mode"
const CapabilityStreaming Capability = "streaming"
const CapabilityToolUse Capability = "tool_use"
const CapabilityVision Capability = "vision"

var enumValues_Capability = []interface{}{
	"tool_use",
	"json_mode",
	"vision",
	"streaming",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Capability) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Capability {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Capability, v)
	}
	*j = Capability(v)
	return nil
}

type Dialect string

const DialectChatCompletions Dialect = "chat_completions"
const DialectGenerateContent Dialect = "generate_content"
const DialectMessages Dialect = "messages"
const DialectRaw Dialect = "raw"

var enumValues_Dialect = []interface{}{
	"chat_completions",
	"messages",
	"generate_content",
	"raw",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Dialect) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Dialect {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Dialect, v)
	}
	*j = Dialect(v)
	return nil
}

// Transport wrapper carrying one event plus its correlation metadata.
type EventEnvelope struct {
	// EmittedAt corresponds to the JSON schema field "emitted_at".
	EmittedAt time.Time `json:"emitted_at" yaml:"emitted_at" mapstructure:"emitted_at"`

	// Event corresponds to the JSON schema field "event".
	Event interface{} `json:"event" yaml:"event" mapstructure:"event"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EventEnvelope) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["emitted_at"]; raw != nil && !ok {
		return fmt.Errorf("field emitted_at in EventEnvelope: required")
	}
	if _, ok := raw["event"]; raw != nil && !ok {
		return fmt.Errorf("field event in EventEnvelope: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in EventEnvelope: required")
	}
	type Plain EventEnvelope
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EventEnvelope(plain)
	return nil
}

// A single observation, attributable to one connector at one moment.
type Evidence struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Kind corresponds to the JSON schema field "kind".
	Kind EvidenceKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// ObservedAt corresponds to the JSON schema field "observed_at".
	ObservedAt time.Time `json:"observed_at" yaml:"observed_at" mapstructure:"observed_at"`

	// Kind-specific body. Phase 1 replaces this with per-kind models.
	Payload EvidencePayload `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`

	// Source corresponds to the JSON schema field "source".
	Source EvidenceSource `json:"source" yaml:"source" mapstructure:"source"`

	// One-line human-readable description.
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

type EvidenceKind string

const EvidenceKindK8SEvent EvidenceKind = "k8s_event"
const EvidenceKindLogCluster EvidenceKind = "log_cluster"
const EvidenceKindManifestDiff EvidenceKind = "manifest_diff"
const EvidenceKindMetricWindow EvidenceKind = "metric_window"
const EvidenceKindPipelineRun EvidenceKind = "pipeline_run"

var enumValues_EvidenceKind = []interface{}{
	"metric_window",
	"log_cluster",
	"manifest_diff",
	"k8s_event",
	"pipeline_run",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EvidenceKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EvidenceKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_EvidenceKind, v)
	}
	*j = EvidenceKind(v)
	return nil
}

// Kind-specific body. Phase 1 replaces this with per-kind models.
type EvidencePayload map[string]interface{}

// Where a piece of Evidence came from, so a human can go look themselves.
type EvidenceSource struct {
	// Connector that produced it, e.g. 'prometheus'.
	Connector string `json:"connector" yaml:"connector" mapstructure:"connector"`

	// Query that produced it, if any.
	Query interface{} `json:"query,omitempty,omitzero" yaml:"query,omitempty" mapstructure:"query,omitempty"`
}

type EvidenceSourceQuery_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *EvidenceSource) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["connector"]; raw != nil && !ok {
		return fmt.Errorf("field connector in EvidenceSource: required")
	}
	type Plain EvidenceSource
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EvidenceSource(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Evidence) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Evidence: required")
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Evidence: required")
	}
	if _, ok := raw["observed_at"]; raw != nil && !ok {
		return fmt.Errorf("field observed_at in Evidence: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in Evidence: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Evidence: required")
	}
	type Plain Evidence
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Evidence(plain)
	return nil
}

// One agent's supported claim about what it observed.
type Finding struct {
	// Codename of the agent that produced it, e.g. 'argus'.
	Agent string `json:"agent" yaml:"agent" mapstructure:"agent"`

	// Agent's own confidence, 0 to 1.
	Confidence float64 `json:"confidence" yaml:"confidence" mapstructure:"confidence"`

	// Evidence supporting the claim. A Finding with none is inadmissible.
	Evidence []Evidence `json:"evidence,omitempty,omitzero" yaml:"evidence,omitempty" mapstructure:"evidence,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Why the Evidence supports the claim.
	Rationale interface{} `json:"rationale,omitempty,omitzero" yaml:"rationale,omitempty" mapstructure:"rationale,omitempty"`

	// Severity corresponds to the JSON schema field "severity".
	Severity Severity `json:"severity" yaml:"severity" mapstructure:"severity"`

	// Title corresponds to the JSON schema field "title".
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

// An agent returned a Finding.
type FindingProducedEvent struct {
	// Finding corresponds to the JSON schema field "finding".
	Finding Finding `json:"finding" yaml:"finding" mapstructure:"finding"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *FindingProducedEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["finding"]; raw != nil && !ok {
		return fmt.Errorf("field finding in FindingProducedEvent: required")
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in FindingProducedEvent: required")
	}
	type Plain FindingProducedEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "finding_produced"
	}
	if plain.Type != "finding_produced" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "finding_produced")
	}
	*j = FindingProducedEvent(plain)
	return nil
}

type FindingRationale_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Finding) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["agent"]; raw != nil && !ok {
		return fmt.Errorf("field agent in Finding: required")
	}
	if _, ok := raw["confidence"]; raw != nil && !ok {
		return fmt.Errorf("field confidence in Finding: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Finding: required")
	}
	if _, ok := raw["severity"]; raw != nil && !ok {
		return fmt.Errorf("field severity in Finding: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return fmt.Errorf("field title in Finding: required")
	}
	type Plain Finding
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 < plain.Confidence {
		return fmt.Errorf("field %s: must be <= %v", "confidence", 1)
	}
	if 0 > plain.Confidence {
		return fmt.Errorf("field %s: must be >= %v", "confidence", 0)
	}
	*j = Finding(plain)
	return nil
}

// One end-to-end run, from trigger to Verdict.
type Investigation struct {
	// CompletedAt corresponds to the JSON schema field "completed_at".
	CompletedAt *time.Time `json:"completed_at,omitempty,omitzero" yaml:"completed_at,omitempty" mapstructure:"completed_at,omitempty"`

	// CreatedAt corresponds to the JSON schema field "created_at".
	CreatedAt time.Time `json:"created_at" yaml:"created_at" mapstructure:"created_at"`

	// Findings corresponds to the JSON schema field "findings".
	Findings []Finding `json:"findings,omitempty,omitzero" yaml:"findings,omitempty" mapstructure:"findings,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Every Delphi model resolution made during this run, in order.
	Resolutions []ResolutionRecord `json:"resolutions,omitempty,omitzero" yaml:"resolutions,omitempty" mapstructure:"resolutions,omitempty"`

	// State corresponds to the JSON schema field "state".
	State InvestigationState `json:"state" yaml:"state" mapstructure:"state"`

	// Trigger corresponds to the JSON schema field "trigger".
	Trigger Trigger `json:"trigger" yaml:"trigger" mapstructure:"trigger"`

	// Absent until the run reaches a conclusion.
	Verdict *InvestigationVerdict `json:"verdict,omitempty,omitzero" yaml:"verdict,omitempty" mapstructure:"verdict,omitempty"`
}

// An Investigation moved out of PENDING.
type InvestigationStartedEvent struct {
	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvestigationStartedEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in InvestigationStartedEvent: required")
	}
	type Plain InvestigationStartedEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "investigation_started"
	}
	if plain.Type != "investigation_started" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "investigation_started")
	}
	*j = InvestigationStartedEvent(plain)
	return nil
}

type InvestigationState string

const InvestigationStateAwaitingApproval InvestigationState = "awaiting_approval"
const InvestigationStateCancelled InvestigationState = "cancelled"
const InvestigationStateCompleted InvestigationState = "completed"
const InvestigationStateFailed InvestigationState = "failed"
const InvestigationStatePending InvestigationState = "pending"
const InvestigationStatePlanning InvestigationState = "planning"
const InvestigationStateRunning InvestigationState = "running"

var enumValues_InvestigationState = []interface{}{
	"pending",
	"planning",
	"running",
	"awaiting_approval",
	"completed",
	"failed",
	"cancelled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvestigationState) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_InvestigationState {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_InvestigationState, v)
	}
	*j = InvestigationState(v)
	return nil
}

// Absent until the run reaches a conclusion.
type InvestigationVerdict struct {
	// Confidence corresponds to the JSON schema field "confidence".
	Confidence float64 `json:"confidence" yaml:"confidence" mapstructure:"confidence"`

	// ContributingFindings corresponds to the JSON schema field
	// "contributing_findings".
	ContributingFindings []Finding `json:"contributing_findings,omitempty,omitzero" yaml:"contributing_findings,omitempty" mapstructure:"contributing_findings,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// RecommendedActions corresponds to the JSON schema field "recommended_actions".
	RecommendedActions []Action `json:"recommended_actions,omitempty,omitzero" yaml:"recommended_actions,omitempty" mapstructure:"recommended_actions,omitempty"`

	// Null when the evidence does not support a conclusion.
	RootCause interface{} `json:"root_cause,omitempty,omitzero" yaml:"root_cause,omitempty" mapstructure:"root_cause,omitempty"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *InvestigationVerdict) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var investigationVerdict_0 InvestigationVerdict_0
	var errs []error
	if err := investigationVerdict_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain InvestigationVerdict
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = InvestigationVerdict(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Investigation) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["created_at"]; raw != nil && !ok {
		return fmt.Errorf("field created_at in Investigation: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Investigation: required")
	}
	if _, ok := raw["state"]; raw != nil && !ok {
		return fmt.Errorf("field state in Investigation: required")
	}
	if _, ok := raw["trigger"]; raw != nil && !ok {
		return fmt.Errorf("field trigger in Investigation: required")
	}
	type Plain Investigation
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Investigation(plain)
	return nil
}

// One model as observed, not as advertised.
//
// Every field below the identity pair is measured by core.llm.probe against
// this deployment, because a model's behaviour behind a particular gateway is
// not always what its vendor documents.
type ModelDescriptor struct {
	// Probed, not declared.
	Capabilities []Capability `json:"capabilities,omitempty,omitzero" yaml:"capabilities,omitempty" mapstructure:"capabilities,omitempty"`

	// ContextWindow corresponds to the JSON schema field "context_window".
	ContextWindow int `json:"context_window,omitempty,omitzero" yaml:"context_window,omitempty" mapstructure:"context_window,omitempty"`

	// InputCostPer1K corresponds to the JSON schema field "input_cost_per_1k".
	InputCostPer1K interface{} `json:"input_cost_per_1k,omitempty,omitzero" yaml:"input_cost_per_1k,omitempty" mapstructure:"input_cost_per_1k,omitempty"`

	// Null means never probed; treat capabilities as unknown.
	LastProbedAt *time.Time `json:"last_probed_at,omitempty,omitzero" yaml:"last_probed_at,omitempty" mapstructure:"last_probed_at,omitempty"`

	// MedianLatencyMs corresponds to the JSON schema field "median_latency_ms".
	MedianLatencyMs interface{} `json:"median_latency_ms,omitempty,omitzero" yaml:"median_latency_ms,omitempty" mapstructure:"median_latency_ms,omitempty"`

	// ModelId corresponds to the JSON schema field "model_id".
	ModelId string `json:"model_id" yaml:"model_id" mapstructure:"model_id"`

	// OutputCostPer1K corresponds to the JSON schema field "output_cost_per_1k".
	OutputCostPer1K interface{} `json:"output_cost_per_1k,omitempty,omitzero" yaml:"output_cost_per_1k,omitempty" mapstructure:"output_cost_per_1k,omitempty"`

	// ProviderId corresponds to the JSON schema field "provider_id".
	ProviderId string `json:"provider_id" yaml:"provider_id" mapstructure:"provider_id"`
}

type ModelDescriptorInputCostPer1K_0 *float64

type ModelDescriptorMedianLatencyMs_0 *int

type ModelDescriptorOutputCostPer1K_0 *float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *ModelDescriptor) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["model_id"]; raw != nil && !ok {
		return fmt.Errorf("field model_id in ModelDescriptor: required")
	}
	if _, ok := raw["provider_id"]; raw != nil && !ok {
		return fmt.Errorf("field provider_id in ModelDescriptor: required")
	}
	type Plain ModelDescriptor
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["context_window"]; !ok || v == nil {
		plain.ContextWindow = 0
	}
	if 0 > plain.ContextWindow {
		return fmt.Errorf("field %s: must be >= %v", "context_window", 0)
	}
	*j = ModelDescriptor(plain)
	return nil
}

// What an agent needs from a model. The only thing an agent may declare.
type ModelRequirements struct {
	// Capabilities the model must demonstrably have.
	Capabilities []Capability `json:"capabilities,omitempty,omitzero" yaml:"capabilities,omitempty" mapstructure:"capabilities,omitempty"`

	// Ceiling for one call. Enforced via core.guardrails.budget.
	MaxCostPerCall interface{} `json:"max_cost_per_call,omitempty,omitzero" yaml:"max_cost_per_call,omitempty" mapstructure:"max_cost_per_call,omitempty"`

	// Minimum context window in tokens.
	MinContext int `json:"min_context,omitempty,omitzero" yaml:"min_context,omitempty" mapstructure:"min_context,omitempty"`

	// Tier corresponds to the JSON schema field "tier".
	Tier Tier `json:"tier,omitempty,omitzero" yaml:"tier,omitempty" mapstructure:"tier,omitempty"`
}

type ModelRequirementsMaxCostPerCall_0 *float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *ModelRequirements) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain ModelRequirements
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["min_context"]; !ok || v == nil {
		plain.MinContext = 0
	}
	if 0 > plain.MinContext {
		return fmt.Errorf("field %s: must be >= %v", "min_context", 0)
	}
	if v, ok := raw["tier"]; !ok || v == nil {
		plain.Tier = "balanced"
	}
	*j = ModelRequirements(plain)
	return nil
}

// Generated from core/contracts/ by codegen/export_schemas.py. Do not edit by
// hand.
type PantheonSchemaJson struct {
	// Action corresponds to the JSON schema field "action".
	Action *Action `json:"action,omitempty,omitzero" yaml:"action,omitempty" mapstructure:"action,omitempty"`

	// AgentManifest corresponds to the JSON schema field "agent_manifest".
	AgentManifest *AgentManifest `json:"agent_manifest,omitempty,omitzero" yaml:"agent_manifest,omitempty" mapstructure:"agent_manifest,omitempty"`

	// EventEnvelope corresponds to the JSON schema field "event_envelope".
	EventEnvelope *EventEnvelope `json:"event_envelope,omitempty,omitzero" yaml:"event_envelope,omitempty" mapstructure:"event_envelope,omitempty"`

	// Evidence corresponds to the JSON schema field "evidence".
	Evidence *Evidence `json:"evidence,omitempty,omitzero" yaml:"evidence,omitempty" mapstructure:"evidence,omitempty"`

	// Finding corresponds to the JSON schema field "finding".
	Finding *Finding `json:"finding,omitempty,omitzero" yaml:"finding,omitempty" mapstructure:"finding,omitempty"`

	// Investigation corresponds to the JSON schema field "investigation".
	Investigation *Investigation `json:"investigation,omitempty,omitzero" yaml:"investigation,omitempty" mapstructure:"investigation,omitempty"`

	// ModelDescriptor corresponds to the JSON schema field "model_descriptor".
	ModelDescriptor *ModelDescriptor `json:"model_descriptor,omitempty,omitzero" yaml:"model_descriptor,omitempty" mapstructure:"model_descriptor,omitempty"`

	// ModelRequirements corresponds to the JSON schema field "model_requirements".
	ModelRequirements *ModelRequirements `json:"model_requirements,omitempty,omitzero" yaml:"model_requirements,omitempty" mapstructure:"model_requirements,omitempty"`

	// ProviderConfig corresponds to the JSON schema field "provider_config".
	ProviderConfig *ProviderConfig `json:"provider_config,omitempty,omitzero" yaml:"provider_config,omitempty" mapstructure:"provider_config,omitempty"`

	// ResolutionRecord corresponds to the JSON schema field "resolution_record".
	ResolutionRecord *ResolutionRecord `json:"resolution_record,omitempty,omitzero" yaml:"resolution_record,omitempty" mapstructure:"resolution_record,omitempty"`

	// Verdict corresponds to the JSON schema field "verdict".
	Verdict *Verdict `json:"verdict,omitempty,omitzero" yaml:"verdict,omitempty" mapstructure:"verdict,omitempty"`
}

// A configured provider. Added from settings, never from code.
type ProviderConfig struct {
	// AuthMode corresponds to the JSON schema field "auth_mode".
	AuthMode AuthMode `json:"auth_mode,omitempty,omitzero" yaml:"auth_mode,omitempty" mapstructure:"auth_mode,omitempty"`

	// Root URL of the provider's API.
	BaseUrl string `json:"base_url" yaml:"base_url" mapstructure:"base_url"`

	// Dialect corresponds to the JSON schema field "dialect".
	Dialect Dialect `json:"dialect" yaml:"dialect" mapstructure:"dialect"`

	// DisplayName corresponds to the JSON schema field "display_name".
	DisplayName string `json:"display_name" yaml:"display_name" mapstructure:"display_name"`

	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty,omitzero" yaml:"enabled,omitempty" mapstructure:"enabled,omitempty"`

	// Stable identifier, e.g. 'local-ollama'.
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Model ids entered by hand when enumeration is absent.
	ManualModels []string `json:"manual_models,omitempty,omitzero" yaml:"manual_models,omitempty" mapstructure:"manual_models,omitempty"`

	// Path used to enumerate models, when the provider offers one.
	ModelsEndpoint interface{} `json:"models_endpoint,omitempty,omitzero" yaml:"models_endpoint,omitempty" mapstructure:"models_endpoint,omitempty"`

	// Name of the credential in the keyring. Never the credential itself.
	SecretRef interface{} `json:"secret_ref,omitempty,omitzero" yaml:"secret_ref,omitempty" mapstructure:"secret_ref,omitempty"`
}

type ProviderConfigModelsEndpoint_0 *string

type ProviderConfigSecretRef_0 *string

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProviderConfig) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["base_url"]; raw != nil && !ok {
		return fmt.Errorf("field base_url in ProviderConfig: required")
	}
	if _, ok := raw["dialect"]; raw != nil && !ok {
		return fmt.Errorf("field dialect in ProviderConfig: required")
	}
	if _, ok := raw["display_name"]; raw != nil && !ok {
		return fmt.Errorf("field display_name in ProviderConfig: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ProviderConfig: required")
	}
	type Plain ProviderConfig
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["auth_mode"]; !ok || v == nil {
		plain.AuthMode = "bearer"
	}
	if v, ok := raw["enabled"]; !ok || v == nil {
		plain.Enabled = true
	}
	*j = ProviderConfig(plain)
	return nil
}

// Why Delphi chose the model it chose, for one call.
//
// Attached to the Investigation so a run is reproducible and can explain its
// own cost without being re-run.
type ResolutionRecord struct {
	// Chosen corresponds to the JSON schema field "chosen".
	Chosen ModelDescriptor `json:"chosen" yaml:"chosen" mapstructure:"chosen"`

	// EstimatedCost corresponds to the JSON schema field "estimated_cost".
	EstimatedCost interface{} `json:"estimated_cost,omitempty,omitzero" yaml:"estimated_cost,omitempty" mapstructure:"estimated_cost,omitempty"`

	// FallbackUsed corresponds to the JSON schema field "fallback_used".
	FallbackUsed bool `json:"fallback_used,omitempty,omitzero" yaml:"fallback_used,omitempty" mapstructure:"fallback_used,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// MatchedStep corresponds to the JSON schema field "matched_step".
	MatchedStep ResolutionStep `json:"matched_step" yaml:"matched_step" mapstructure:"matched_step"`

	// Human-readable reason per rejected candidate, in evaluation order.
	Rejected []string `json:"rejected,omitempty,omitzero" yaml:"rejected,omitempty" mapstructure:"rejected,omitempty"`

	// Agent codename that consulted Delphi, e.g. 'hermes'.
	RequestedBy string `json:"requested_by" yaml:"requested_by" mapstructure:"requested_by"`

	// Requirements corresponds to the JSON schema field "requirements".
	Requirements ModelRequirements `json:"requirements" yaml:"requirements" mapstructure:"requirements"`

	// ResolvedAt corresponds to the JSON schema field "resolved_at".
	ResolvedAt time.Time `json:"resolved_at" yaml:"resolved_at" mapstructure:"resolved_at"`
}

type ResolutionRecordEstimatedCost_0 *float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResolutionRecord) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["chosen"]; raw != nil && !ok {
		return fmt.Errorf("field chosen in ResolutionRecord: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in ResolutionRecord: required")
	}
	if _, ok := raw["matched_step"]; raw != nil && !ok {
		return fmt.Errorf("field matched_step in ResolutionRecord: required")
	}
	if _, ok := raw["requested_by"]; raw != nil && !ok {
		return fmt.Errorf("field requested_by in ResolutionRecord: required")
	}
	if _, ok := raw["requirements"]; raw != nil && !ok {
		return fmt.Errorf("field requirements in ResolutionRecord: required")
	}
	if _, ok := raw["resolved_at"]; raw != nil && !ok {
		return fmt.Errorf("field resolved_at in ResolutionRecord: required")
	}
	type Plain ResolutionRecord
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["fallback_used"]; !ok || v == nil {
		plain.FallbackUsed = false
	}
	*j = ResolutionRecord(plain)
	return nil
}

type ResolutionStep string

const ResolutionStepAgentBinding ResolutionStep = "agent_binding"
const ResolutionStepGlobalDefault ResolutionStep = "global_default"
const ResolutionStepTaskOverride ResolutionStep = "task_override"
const ResolutionStepTierDefault ResolutionStep = "tier_default"

var enumValues_ResolutionStep = []interface{}{
	"task_override",
	"agent_binding",
	"tier_default",
	"global_default",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResolutionStep) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResolutionStep {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ResolutionStep, v)
	}
	*j = ResolutionStep(v)
	return nil
}

type Severity string

const SeverityCritical Severity = "critical"
const SeverityHigh Severity = "high"
const SeverityInfo Severity = "info"
const SeverityLow Severity = "low"
const SeverityMedium Severity = "medium"

var enumValues_Severity = []interface{}{
	"info",
	"low",
	"medium",
	"high",
	"critical",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Severity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Severity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Severity, v)
	}
	*j = Severity(v)
	return nil
}

type Tier string

const TierBalanced Tier = "balanced"
const TierCheap Tier = "cheap"
const TierFrontier Tier = "frontier"

var enumValues_Tier = []interface{}{
	"cheap",
	"balanced",
	"frontier",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Tier) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_Tier {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_Tier, v)
	}
	*j = Tier(v)
	return nil
}

// The inbound event that started everything.
type Trigger struct {
	// Kind corresponds to the JSON schema field "kind".
	Kind TriggerKind `json:"kind" yaml:"kind" mapstructure:"kind"`

	// Payload corresponds to the JSON schema field "payload".
	Payload TriggerPayload `json:"payload,omitempty,omitzero" yaml:"payload,omitempty" mapstructure:"payload,omitempty"`

	// ReceivedAt corresponds to the JSON schema field "received_at".
	ReceivedAt time.Time `json:"received_at" yaml:"received_at" mapstructure:"received_at"`

	// Who sent it, e.g. 'alertmanager'.
	Source string `json:"source" yaml:"source" mapstructure:"source"`
}

type TriggerKind string

const TriggerKindAlert TriggerKind = "alert"

type InvestigationVerdict_0 = Verdict

// UnmarshalJSON implements json.Unmarshaler.
func (j *Trigger) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["kind"]; raw != nil && !ok {
		return fmt.Errorf("field kind in Trigger: required")
	}
	if _, ok := raw["received_at"]; raw != nil && !ok {
		return fmt.Errorf("field received_at in Trigger: required")
	}
	if _, ok := raw["source"]; raw != nil && !ok {
		return fmt.Errorf("field source in Trigger: required")
	}
	type Plain Trigger
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Trigger(plain)
	return nil
}

type VerdictRootCause_0 *string

// The orchestrator's ranked conclusion for one Investigation.
type Verdict struct {
	// Confidence corresponds to the JSON schema field "confidence".
	Confidence float64 `json:"confidence" yaml:"confidence" mapstructure:"confidence"`

	// ContributingFindings corresponds to the JSON schema field
	// "contributing_findings".
	ContributingFindings []Finding `json:"contributing_findings,omitempty,omitzero" yaml:"contributing_findings,omitempty" mapstructure:"contributing_findings,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// RecommendedActions corresponds to the JSON schema field "recommended_actions".
	RecommendedActions []Action `json:"recommended_actions,omitempty,omitzero" yaml:"recommended_actions,omitempty" mapstructure:"recommended_actions,omitempty"`

	// Null when the evidence does not support a conclusion.
	RootCause interface{} `json:"root_cause,omitempty,omitzero" yaml:"root_cause,omitempty" mapstructure:"root_cause,omitempty"`

	// Summary corresponds to the JSON schema field "summary".
	Summary string `json:"summary" yaml:"summary" mapstructure:"summary"`
}

var enumValues_TriggerKind = []interface{}{
	"alert",
	"webhook",
	"schedule",
	"human_question",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *TriggerKind) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_TriggerKind {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_TriggerKind, v)
	}
	*j = TriggerKind(v)
	return nil
}

type TriggerPayload map[string]interface{}

const TriggerKindWebhook TriggerKind = "webhook"
const TriggerKindSchedule TriggerKind = "schedule"
const TriggerKindHumanQuestion TriggerKind = "human_question"

// The aggregator reached a conclusion.
type VerdictReadyEvent struct {
	// InvestigationId corresponds to the JSON schema field "investigation_id".
	InvestigationId string `json:"investigation_id" yaml:"investigation_id" mapstructure:"investigation_id"`

	// Type corresponds to the JSON schema field "type".
	Type string `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Verdict corresponds to the JSON schema field "verdict".
	Verdict Verdict `json:"verdict" yaml:"verdict" mapstructure:"verdict"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *VerdictReadyEvent) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in VerdictReadyEvent: required")
	}
	if _, ok := raw["verdict"]; raw != nil && !ok {
		return fmt.Errorf("field verdict in VerdictReadyEvent: required")
	}
	type Plain VerdictReadyEvent
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["type"]; !ok || v == nil {
		plain.Type = "verdict_ready"
	}
	if plain.Type != "verdict_ready" {
		return fmt.Errorf("field %s: must be equal to %s", "type", "verdict_ready")
	}
	*j = VerdictReadyEvent(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Verdict) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["confidence"]; raw != nil && !ok {
		return fmt.Errorf("field confidence in Verdict: required")
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Verdict: required")
	}
	if _, ok := raw["investigation_id"]; raw != nil && !ok {
		return fmt.Errorf("field investigation_id in Verdict: required")
	}
	if _, ok := raw["summary"]; raw != nil && !ok {
		return fmt.Errorf("field summary in Verdict: required")
	}
	type Plain Verdict
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if 1 < plain.Confidence {
		return fmt.Errorf("field %s: must be <= %v", "confidence", 1)
	}
	if 0 > plain.Confidence {
		return fmt.Errorf("field %s: must be >= %v", "confidence", 0)
	}
	*j = Verdict(plain)
	return nil
}
