"""Guards that the public repository claims no AI authorship.

The repository is public. Which local tools a contributor happens to use is
their business and must not be recorded in tracked files. See
docs/adr/0003-neutral-repository-documentation.md.

## What is banned: attribution, not vendors

This guard matches *authorship attribution patterns* - a co-author trailer
naming an assistant, a "generated by" footer, an emoji sign-off, a reference to
an assistant's local pointer file or config directory.

It deliberately does **not** ban vendor names, model identifiers or API hosts.
Those are product functionality: Pantheon is an LLM platform, so its docs and
config legitimately name providers, list example models and document dialects -
exactly as ADR 0001 names MinIO, S3 and Ceph. Nobody infers AI authorship from a
supported-providers table; every tool in this space ships one.

An earlier version banned vendor substrings outright. That was the wrong shape:
it blocked legitimate product content while catching nothing extra, since
attribution is a phrase, not a word.

`test_guard_permits_provider_documentation` pins that distinction so the rule
cannot be quietly re-broadened.

Scope: *tracked* files only, via `git ls-files`. Untracked and gitignored files
are deliberately out of scope - local pointer files are permitted precisely
because they never enter the repository. Commit messages are not checked here;
see the ADR.

Phase: 0 - Scaffold & Tooling
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from tests.mechanism import read_scannable, read_verbatim

REPO_ROOT = Path(__file__).resolve().parents[2]

# Names that identify an AI coding assistant rather than a model vendor. Used
# only as the object of an attribution phrase, never on its own.
_ASSISTANT = (
    r"(?:claude\s*code|claude|chatgpt|gpt-[0-9]|copilot|codex|cursor|"
    r"an?\s+ai|ai\s+(?:assistant|agent|model))"
)

# (pattern, human-readable reason). Matched case-insensitively.
ATTRIBUTION_PATTERNS: tuple[tuple[str, str], ...] = (
    (rf"co-authored-by:[^\n]*{_ASSISTANT}", "co-author trailer naming an assistant"),
    (
        rf"(?:generated|created|written|authored|produced)\s+(?:with|by)\s+[^\n]{{0,40}}?{_ASSISTANT}",
        "authorship attributed to an assistant",
    ),
    (r"\N{ROBOT FACE}", "robot-emoji sign-off"),
    (r"claude\.md", "assistant pointer filename"),
    (r"(?<![\w.-])\.claude/", "assistant config directory"),
)

_COMPILED = tuple((re.compile(p, re.IGNORECASE), why) for p, why in ATTRIBUTION_PATTERNS)

# This scanner necessarily spells the patterns out, so it excludes itself.
# Every other tracked file is scanned.
SELF = Path(__file__).resolve()


def _violations(text: str) -> list[str]:
    """Return a reason for each attribution pattern present in text."""
    return [why for pattern, why in _COMPILED if pattern.search(text)]


def _tracked_files() -> list[Path]:
    """Every file git tracks, as absolute paths."""
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=REPO_ROOT,
        capture_output=True,
        check=True,
        text=True,
    )
    return [REPO_ROOT / name for name in result.stdout.split("\0") if name and name.strip()]


# ---------------------------------------------------------------------------
# The rule, in both directions
# ---------------------------------------------------------------------------


def test_guard_permits_provider_documentation() -> None:
    """Vendor names, model ids and API hosts are product content, not attribution.

    This test exists to stop the guard being re-broadened into a vendor-substring
    ban. If it starts failing, the guard has drifted - fix the guard, not this
    test.
    """
    sample = """
    | Provider     | Dialect           | Example model          |
    |--------------|-------------------|------------------------|
    | OpenRouter   | chat_completions  | openai/gpt-4o-mini     |
    | Groq         | chat_completions  | llama-3.3-70b-versatile|
    | Anthropic    | messages          | claude-sonnet-4        |
    | Google       | generate_content  | gemini-2.0-flash       |
    | DeepSeek     | chat_completions  | deepseek-chat          |
    | Ollama       | chat_completions  | qwen2.5:14b            |

    Endpoints: https://api.anthropic.com/v1/messages,
               https://api.openai.com/v1/chat/completions
    Set PANTHEON_LLM_MODEL=claude-sonnet-4 to pin the frontier tier.
    """
    assert _violations(sample) == []


def test_guard_catches_authorship_attribution() -> None:
    """The patterns that matter are still caught."""
    cases = (
        "Co-Authored-By: Claude <noreply@example.com>",
        "Generated with Claude Code",
        "This module was written by an AI assistant.",
        "\N{ROBOT FACE} generated",
        "See CLAUDE.md for the repository map",
        "config lives in .claude/settings.json",
    )
    for case in cases:
        assert _violations(case), f"guard failed to catch: {case!r}"


# ---------------------------------------------------------------------------
# Applied to the repository
# ---------------------------------------------------------------------------


def test_no_attribution_in_tracked_paths() -> None:
    """No tracked file is named after an assistant tool."""
    offenders = [
        f"{path.relative_to(REPO_ROOT)} -> {reasons}"
        for path in _tracked_files()
        if (reasons := _violations(path.as_posix()))
    ]
    assert not offenders, f"tracked paths claiming AI authorship: {offenders}"


def test_no_attribution_in_tracked_contents() -> None:
    """No tracked file attributes its authorship to an assistant."""
    offenders: list[str] = []

    for path in _tracked_files():
        if path.resolve() == SELF or not path.is_file():
            continue
        text = read_scannable(path)
        if reasons := _violations(text):
            offenders.append(f"{path.relative_to(REPO_ROOT)} -> {reasons}")

    assert not offenders, "tracked files claiming AI authorship:\n  " + "\n  ".join(offenders)


def test_repository_map_is_tracked_and_canonical() -> None:
    """docs/REPOSITORY_MAP.md is the committed map, and it is substantial.

    A neutralisation that quietly dropped the map instead of moving it would
    pass the tests above while destroying the thing they protect.
    """
    tracked = {path.relative_to(REPO_ROOT).as_posix() for path in _tracked_files()}
    assert "docs/REPOSITORY_MAP.md" in tracked

    body = read_verbatim(
        REPO_ROOT / "docs" / "REPOSITORY_MAP.md",
        why="Markdown headings start with # and would be stripped",
    )
    for heading in (
        "## Project identity",
        "## Language boundaries",
        "## Folder map",
        "## Where do I put X?",
        "## Generated files",
        "## Standing decisions",
        "## Git Flow rules",
        "## Commands",
        "## Phase roadmap",
        "## Structure changelog",
    ):
        assert heading in body, f"repository map is missing section: {heading}"
