{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pantheon.fullname" . }}-api
  labels:
    {{- include "pantheon.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
  selector:
    {{- include "pantheon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
